; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    majicdesigns/MD_Parola@^3.7.3
    majicdesigns/MD_MAX72XX@^3.5.1
    bblanchon/ArduinoJson@^7.1.0

build_flags =
    -D CORE_DEBUG_LEVEL=1
